# Generated by Django 6.0.7 on 2026-07-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApplication', '0002_remove_purchase_notes_remove_purchase_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='item_type',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item_name',
            field=models.CharField(choices=[('soya', 'Soya'), ('sunflower', 'Sunflower'), ('medicine', 'Medicine'), ('equipment', 'Equipment'), ('other', 'Other')], default='soya', max_length=100),
        ),
    ]
