# Generated by Django 6.0.7 on 2026-07-11 18:06

from decimal import Decimal

from django.db import migrations, models


def recalculate_purchase_stock(apps, schema_editor):
    Purchase = apps.get_model('FarmApplication', 'Purchase')
    FeedMix = apps.get_model('FarmApplication', 'FeedMix')
    item_names = ['soya', 'sunflower', 'medicine', 'equipment', 'other']

    for item_name in item_names:
        mixed_quantity = sum(
            FeedMix.objects.filter(ingredient=item_name).values_list('quantity_kg', flat=True),
            Decimal('0.00'),
        )
        remaining_mixed_quantity = mixed_quantity

        purchases = Purchase.objects.filter(item_name=item_name).order_by('purchase_date', 'id')
        for purchase in purchases:
            used_quantity = min(purchase.quantity, remaining_mixed_quantity)
            purchase.stock = purchase.quantity - used_quantity
            purchase.save(update_fields=['stock'])
            remaining_mixed_quantity -= used_quantity


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApplication', '0003_remove_purchase_item_type_alter_purchase_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feedmix',
            name='ingredient',
            field=models.CharField(choices=[('soya', 'Soya'), ('sunflower', 'Sunflower'), ('medicine', 'Medicine'), ('equipment', 'Equipment'), ('other', 'Other')], default='soya', max_length=100),
        ),
        migrations.RunPython(recalculate_purchase_stock, migrations.RunPython.noop),
    ]
