# Generated by Django 6.0.7 on 2026-07-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApplication', '0004_purchase_stock_alter_feedmix_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='purchase',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedmix',
            name='ingredient',
            field=models.CharField(choices=[('soya', 'Soya'), ('sunflower', 'Sunflower'), ('maize_bran', 'Maize Bran'), ('cotton_seed_cake', 'Cotton Seed Cake'), ('fish_meal', 'Fish Meal'), ('limestone', 'Limestone'), ('premix', 'Premix'), ('medicine', 'Medicine'), ('equipment', 'Equipment'), ('other', 'Other')], default='soya', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item_name',
            field=models.CharField(choices=[('soya', 'Soya'), ('sunflower', 'Sunflower'), ('maize_bran', 'Maize Bran'), ('cotton_seed_cake', 'Cotton Seed Cake'), ('fish_meal', 'Fish Meal'), ('limestone', 'Limestone'), ('premix', 'Premix'), ('medicine', 'Medicine'), ('equipment', 'Equipment'), ('other', 'Other')], default='soya', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['item_name', 'purchase_date'], name='FarmApplica_item_na_e72667_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier'], name='FarmApplica_supplie_032753_idx'),
        ),
    ]
