# Generated by Django 6.0.7 on 2026-07-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApplication', '0005_alter_purchase_options_purchase_invoice_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchase',
            name='FarmApplica_supplie_032753_idx',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='unit',
        ),
    ]
