# Generated by Django 6.0.7 on 2026-07-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApplication', '0006_remove_purchase_farmapplica_supplie_032753_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='invoice_number',
        ),
    ]
