# Generated by Django 6.0.7 on 2026-07-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApplication', '0011_remove_feedconsumption_flock_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggproduction',
            name='flock_name',
        ),
    ]
