# Generated by Django 6.0.7 on 2026-08-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApplication', '0012_remove_eggproduction_flock_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eggproduction',
            options={'verbose_name': 'Egg Production', 'verbose_name_plural': 'Egg Production'},
        ),
        migrations.AlterModelOptions(
            name='feedconsumption',
            options={'verbose_name': 'Feed Consumption', 'verbose_name_plural': 'Feed Consumption'},
        ),
        migrations.AlterModelOptions(
            name='feedmix',
            options={'ordering': ['-mixed_date', '-created_at'], 'verbose_name': 'Feed Mix', 'verbose_name_plural': 'Feed Mixes'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date', '-created_at'], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
    ]
